name: 'Code Coverage Report'
description: 'Creates and adjust the code coverage report'
inputs:
  cobertura:
    description: 'The file path of the cobertura code coverage report.'
    required: true
    default: './coverage/report/cobertura-coverage.xml'
  html:
    description: 'The file path of the entry point of the HTML code coverage report.'
    required: true
    default: './coverage/report/index.html'
runs:
  using: 'composite'
  steps:
    - name: Generate Code Coverage Markdown
      uses: irongut/CodeCoverageSummary@v1.3.0
      with:
        filename: ${{ inputs.cobertura }}
        badge: true
        fail_below_min: true
        format: markdown
        output: both
        thresholds: '50 85'

    - name: Add Coverage PR Comment
      uses: marocchino/sticky-pull-request-comment@v2
      if: github.event_name == 'pull_request'
      with:
        recreate: true
        path: code-coverage-results.md
