name: 'Code Coverage Report'
description: 'Creates and adjust the code coverage report'
inputs:
  report-directory:
    description: 'The directory with the code coverage reports.'
    required: true
    default: './coverage/report'
runs:
  using: 'composite'
  steps:
    - name: Generate Code Coverage Markdown
      uses: irongut/CodeCoverageSummary@v1.3.0
      with:
        filename: ${{ inputs.report-directory }}/cobertura-coverage.xml
        badge: true
        fail_below_min: true
        format: markdown
        output: both
        thresholds: '50 85'

    - name: Add Link to Code Coverage HTML
      run: sed 's/\(!\[Code Coverage\].*\)/[\1](.\/index.html)/' code-coverage-results.md > ${{ inputs.report-directory }}/code-coverage-results.md

    - name: Add Coverage PR Comment
      uses: marocchino/sticky-pull-request-comment@v2
      if: github.event_name == 'pull_request'
      with:
        recreate: true
        path: ${{ inputs.report-directory }}/code-coverage-results.md
