name: 'Code Coverage Report'
description: 'Creates and adjust the code coverage report'

permissions:
  contents: read
  pages: write
  id-token: write

inputs:
  report-directory:
    description: 'The directory with the code coverage reports.'
    required: true
    default: './coverage/report'

runs:
  using: 'composite'
  steps:
    - name: Generate Code Coverage Markdown
      uses: irongut/CodeCoverageSummary@v1.3.0
      with:
        filename: ${{ inputs.report-directory }}/cobertura-coverage.xml
        badge: true
        fail_below_min: true
        format: markdown
        output: both
        thresholds: '50 85'

    - name: Add Coverage PR Comment
      uses: marocchino/sticky-pull-request-comment@v2
      if: github.event_name == 'pull_request'
      with:
        recreate: true
        path: code-coverage-results.md

    - name: Download Coverage Badge
      #if: github.ref == 'refs/heads/main'
      shell: bash
      run: wget `cat code-coverage-results.md | head -n 1 | sed 's/!\[Code Coverage\](\([^?]*\).*/\1.svg/'` -O ./coverage/coverage.svg

    - name: Setup Pages
      #if: github.ref == 'refs/heads/main'
      uses: actions/configure-pages@v3

    - name: Upload Coverage
      #if: github.ref == 'refs/heads/main'
      uses: actions/upload-pages-artifact@v1
      with:
        path: './coverage'

    - name: Deploy to GitHub Pages
      #if: github.ref == 'refs/heads/main'
      id: deployment
      uses: actions/deploy-pages@v2
